### ISSUE TITLE
[NOT AN ISSUE] Any guide how to make custom engine?

### ISSUE THREAD

**Issue by NyanAlex** [Buckminsterfullerene02/UE-Modding-Tools#4]
I want to make a mod for a game that uses its own unreal engine, are there any guides?

**Comment by Buckminsterfullerene02** [comment]
Assuming you're talking about [blueprint mods](https://github.com/Dmgvol/UE_Modding/tree/main?tab=readme-ov-file#advanced-modding); in many cases you don't actually need to replicate engine edits done by the game to mod it - but it all depends on what exactly they edited. 

If modding the game without custom engine doesn't work for whatever reason, you can try using UE4SS to do a [UHT dump](https://docs.ue4ss.com/guides/generating-uht-compatible-headers.html) on the game, which includes information about engine modules, which you can use to diff on the base engine version that the game uses, and then make the changes required in the custom engine. 

This has been done for a few uprojects for modding games, most recently for [Black Myth Wukong](https://github.com/kboykboy2/UnrealEngine/tree/5.0-BlackMythWukong). You can check out the commits they've done that pull in headers from the UHT dump into the engine in order to create parity with the original engine.

If you have any further queries, I recommend talking to `@Narknon` on the [UE modding discord](https://discord.gg/vwBdWYTBTf), as he's done quite a few of these custom engines now.

**Comment by NyanAlex** [comment]
Thank you for answer! I couldn't find information about this anywhere

**Comment by NyanAlex** [comment]
but how do I find out what exactly is modified in the engine?
